# Generated by Django 4.2.11 on 2024-09-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40, unique=True)),
            ],
        ),
    ]
