# Generated by Django 4.2.11 on 2024-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author_name', models.CharField(max_length=15)),
                ('author_surname', models.CharField(max_length=20)),
                ('page_num', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
